package it.snorcini.dev.orderplanner.entity;

import it.snorcini.dev.orderplanner.error.OrderPlannerValidationErrors;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

/**
 * DTO used for creation of an Order.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Validated
@Builder
public class Coordinate {

    @Valid
    @NotNull(message = OrderPlannerValidationErrors.LATITUDE_NULL)
    protected Double latitude;

    @Valid
    @NotNull(message = OrderPlannerValidationErrors.LONGITUDE_NULL)
    protected Double longitude;
}
