package it.snorcini.dev.orderplanner.entity;

import it.snorcini.dev.orderplanner.error.OrderPlannerValidationErrors;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

/**
 * DTO used for creation of a Book.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Validated
public class Package {

    @Valid
    @NotNull(message = OrderPlannerValidationErrors.DESCRIPTION_NULL)
    @Size(max = 255)
    protected String description;

    @Valid
    @NotNull(message = OrderPlannerValidationErrors.COORDINATE_NULL)
    protected Coordinate destination;
}
