package it.snorcini.dev.orderplanner.dto;

import it.snorcini.dev.orderplanner.result.OrderPlannerResults;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * Generic response object returned by controller
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@SuperBuilder
public class OrderPlannerBaseResponse {

    /**
     * Operation result code.
     *
     * @see OrderPlannerResults
     */
    @NotNull
    protected Integer resultCode;
    /**
     * Description of result
     */
    protected String resultMessage;
    /**
     * Other information like validation error
     */
    protected List<String> resultInfo;
}
