package it.snorcini.dev.orderplanner.dto;

import jakarta.validation.Valid;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Data;

import java.util.List;

/**
 * DTO returned to the caller, contains a list of Books.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 * This class @extends {@link OrderPlannerBaseResponse} contains
 * generic response data.
 */
@Builder
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class OrderListResponse extends OrderPlannerBaseResponse {

    /**
     * The list of books.
     */
    @Valid
    private List<UpdateOrderDTO> payload;

}
