package it.snorcini.dev.orderplanner.dto;

import it.snorcini.dev.orderplanner.error.OrderPlannerValidationErrors;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

import java.util.List;

/**
 * DTO used for creation of a Book.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Validated
public class OrderDTO  {

    @NotNull(message = OrderPlannerValidationErrors.ORDERS_NULL)
    protected List<it.snorcini.dev.orderplanner.entity.Package> packages;

}
