package it.snorcini.dev.orderplanner.dto;

import it.snorcini.dev.orderplanner.entity.Coordinate;
import jakarta.validation.Valid;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * DTO returned to the caller, contains a list of Books.
 * <p>
 * Methods are auto-generated by Lombok.
 * <p>
 * This class @extends {@link OrderPlannerBaseResponse} contains
 * generic response data.
 */
@SuperBuilder
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class PlanResponse extends OrderPlannerBaseResponse {

    /**
     * The delivery path.
     */
    @Valid
    private List<Coordinate> plan;

}
