server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    root: ${LOGGING_LEVEL:DEBUG}
spring:
  data:
    mongodb:
      uri: "mongodb://order-planner-mongodb:27017/orderplanner"
  banner:
    location: order-planner-banner.logo
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    show-sql: ${SHOW_SQL:false}
